load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
	name = "State",
	srcs = [
		"main.cpp", "states/State.cpp", "states/State.h", "TrafficLight.cpp", "TrafficLight.h",
		"states/Red.cpp", "states/Red.h", "states/Yellow.cpp", "states/Yellow.h", "states/Green.cpp", "states/Green.h"
	],
	visibility = ["//visibility:public"],
)