load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_binary(
	name = "Prototype",
	srcs = [
		"main.cpp",
		"Prototype.cpp",
		"Prototype.h",
		"FerrariPrototype.cpp",
		"FerrariPrototype.h",
		"PirelliFerrari.cpp",
		"PirelliFerrari.h"
	],
	visibility = ["//visibility:public"],
)